# Generated by Django 3.2.9 on 2021-11-25 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Powtoon', '0005_powtoon_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powtoon',
            name='connection',
            field=models.ManyToManyField(blank=True, related_name='connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
